dist: xenial
branches:
  only:
    - master
language: csharp
solution: ServiceOuterInnerResourcePlugin.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - echo 'deb http://www.rabbitmq.com/debian/ testing main' | sudo tee /etc/apt/sources.list.d/rabbitmq.list
  - wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rabbitmq-server
  - sudo systemctl enable rabbitmq-server
  - sudo systemctl start rabbitmq-server
  - sudo rabbitmqctl add_user admin password 
  - sudo rabbitmqctl set_user_tags admin administrator
  - sudo rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  - sudo rabbitmq-plugins enable rabbitmq_management	
  - wget http://localhost:15672/cli/rabbitmqadmin
  - chmod +x rabbitmqadmin
  - ./rabbitmqadmin declare queue name=eformsdk-input durable=true
  - ./rabbitmqadmin declare queue name=eform-service-outer-inner-resource-plugin durable=true
  - dotnet restore
  - dotnet build ServiceOuterInnerResourcePlugin.sln
  - dotnet test -v n ServiceOuterInnerResourcePlugin.Integration.Test/ServiceOuterInnerResourcePlugin.Integration.Test.csproj
